Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [ ]:
import numpy as np

D = np.diag([1, 2, 3])
D_inv = np.linalg.inv(D)
print(np.dot(D, D_inv)) #행렬곱 연산 수행시 단위 행렬 나옴 따러서 역행렬 존재하고 역행렬 맞음

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [ ]:
#상삼각 행렬은 아래에 0이 있는 형태의 행렬
a_upper = np.triu(np.ones((5,5)))
print(a_upper)
#전치하여 하삼각행렬 만든것과 비교
a_lower_T = a_upper.T
print(a_lower_T)
a_lower = np.tril(np.ones((5,5)))
print(a_lower)
#같은지 확인하기 위해 np.allclose 사용
np.allclose(a_lower_T,a_lower) #True 이므로 같음

[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


True

In [ ]:
#ex
U = np.array([[1,2,3],[0,4,5],[0,0,6]])
U_T = U.T

Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [ ]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv)) # 행렬곱 수행이 단위행렬 나오므로 역행렬이 맞음

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [ ]:
#ex
i = np.eye(2)
#np.allclose(i, A)로 비교
# [[ 1.00000000e+00 -1.11022302e-16]
#  [ 1.11022302e-16  1.00000000e+00]]
#이렇게 나와도 np.allclose() True로 나옴

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3]) #데이터 포인트
레이어 1개 가정, 비활성화 함수도 쓰지 않음
 - 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ(가중치)를 정의.
 - 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [ ]:
X = np.array([1, 2, 3]) #데이터 포인트
print(X.shape)
para = np.array([[2,4],[5,2],[2,1]]) #가중치 파라미터
print(para.shape)
y = np.dot(X, para) #행렬곱
print(y, y.shape)


(3,)
(3, 2)
[18 11] (2,)


In [ ]:
#ex.
X = np.array([1, 2, 3]) #행백터
#모델 파라미터(bias, w1, w2) - 일차원 벡터로 만듬
theta = np.array([0.5,1.5,-2])
#예측치
y_pred = np.dot(X,theta)

#### 행렬곱을 할 때 연산의 순서
연산의 순서는 매우 중요하며, 결과가 달라질 수 있습니다. 주어진 입력과 가중치에 대해 원하는 연산이 무엇인지에 따라 올바른 순서를 선택

np.dot(X,W)와 np.dot(W,X)
- np.dot(X,W)는 X가 (1x3) 벡터이고, W가 (3x3) 행렬이므로, 결과는 (1x3) 벡터입니다.
- np.dot(W,X)는 W가 (3x3) 행렬이고, X가 (3,) 벡터이므로, 결과는 (3,) 벡터입니다.
- 둘 중 어느 것을 선택해야 하는지는 연산의 의미에 따라 결정
  - 입력 벡터 X를 가중치 행렬 W에 곱하여 새로운 출력 벡터를 계산하는 경우
  np.dot(X,W)를 사용.
  - 가중치 행렬 W를 입력 벡터 X에 곱하여 각 출력 뉴런에 대한 값을 계산하는 경우 np.dot(W,X)를 사용.

In [2]:
import numpy as np
X = np.array([1,2,3])
W = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(np.dot(X,W)) #1x3 3x3 => 1x3
print(np.dot(W,X)) #3x3 3x1 => 3x1


[30 36 42]
[14 32 50]


In [ ]:
X = np.array([[1],[2],[3]])
W = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(np.dot(W,X)) #(3,3)@(3,1) => (3,1)
#print(np.dot(X,W)) #(3,1)@(3,3) 에러

 Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.
X = np.array([0.5, 1.0, -1.5])
레이어 1개 가정, 비활성화 함수도 쓰지 않음
 - 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
 - 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [ ]:
X = np.array([0.5, 1.0, -1.5])
W = np.array([1,2,3])    #가중치 행렬
y = np.dot(X, W)        #행렬곱
print(y)

-2.0


In [ ]:
#ex. 모델 파라미터와 가중치 행렬이 같은 말
#W는 가중치 행렬, X는 입력 벡터이고 일반적인 표기 방식은 WX
W = np.array([[1,5,2],
              [6,2,-9],
              -2,6,2]])

y = np.dot(X,W) # 이게 맞는 표현, 가중치 먼저 그다음 입력 벡터, 표기만 이렇게 해준다고 생각해야
# 표현 : (3x3)@ (1x3)자동 트랜스포즈=> (3x1)
# 실제 : (1x3)@(3x3) => (1x3)

Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.(편향벡터 랜덤하게 만들기) =>결과가 Z
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산

활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
import numpy as np

X = np.array([1, -2, 3])
W = np.array([-1,-2,3])
b = np.array([4,-5,6])
Z = np.dot(X, W)        #입력벡터와 가중치 행렬곱
Z = np.dot(Z, b)        #위 결과에 편향벡터 행렬곱
print(Z)
def relu(z):
    return np.maximum(0, z) #비선형
print(relu(Z))

def sigmoid(z): #분류 모델로 씀, 0.5를 기준으로 판단 성공은 1 실패는 0
    return 1/(1 + np.exp(-z)) #임계치를 0.5기준, 0.5이상은 1, 이하는 0  , 비선형 변환
print(sigmoid(Z))

[ 48 -60  72]
[48  0 72]
[1.00000000e+00 8.75651076e-27 1.00000000e+00]


In [ ]:
#ex
X = np.array([1, -2, 3])

Z = np.dot(X,W) + b #편향은 그냥 더하기 , Z은 선형 변환까지 완료
#활성화 함수 적용하면 비선형 변환 완료


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [ ]:
A = np.array([[3,4], [2,1]])        #계수행렬
print(A, A.shape,'\n')
b = np.array([10,5])                #결과벡터
print(b, b.shape,'\n')
A_inv = np.linalg.inv(A)            #계수행렬의 역행렬
print(A_inv, A_inv.shape,'\n')
x = np.dot(b,A_inv)                #역행렬과 결과벡터의 행렬곱
print(x,'\n')
#A와 b의 행렬곱은?
print(np.dot(b, A_inv)) #뭔지 모름 한번 해봄

[[3 4]
 [2 1]] (2, 2) 

[10  5] (2,) 

[[-0.2  0.8]
 [ 0.4 -0.6]] (2, 2) 

[2. 1.] 

[0. 5.]


[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [ ]:
#ex
Ax = b
x = b/A
x = A역행렬 * b

Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p'를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p'에서 원래 좌표 p를 복원.

In [ ]:
p = np.array([1, 2])    #2차원상 점
T = np.array([[2, 0], [0, 3]])
new_p = np.dot(p,T)        #새로운 p의 좌표 계산
print(f'New p : {new_p}')
T_inv = np.linalg.inv(T)    #변환 행렬의 역행렬
original_p = np.dot(T_inv, new_p)   #변환행렬의 역행렬과 새로운 좌표를 행렬곱
print(f'Original p : {original_p.astype(int)}')

New p : [2 6]
Original p : [1 2]


In [ ]:
#ex
np.dot(X,W) #표현에만 유의