선형대수 - 학원에서 대부분 안함

ai 네트웍이나 머신러닝 알고리즘에 선형대수를 사용

응용을 하려면 기본을 알고 있어야 함

포인트 - 신경망이나 머신러닝에서 중요한게 학습

어떤 과정을 거쳐 가중치를 주는지

선형대수를 알아야 가중치 업데이트하는 부분에 적용

선형변환에 대해 알려면 선형대수를 알아야함

그정도를 이해하기 위해 선형대수를 하자

미분도 해야함, 가중치 학습이 순정파, 역전파 반복

거기에서 그레디언트 구해야하는데 편미분 할수 있어야 함

선형대수, 편미분 이해가 필요

딥러닝 네트웍 이해에 도움이 됨

백터와 행렬간의 행렬곱

어떻게 선형변환이 이루어지는가?



Task1_0610. 주어진 두 배열 arr1과 arr2에서, arr2의 요소가 10보다 큰 위치의 arr1 요소들을 선택하세요.

arr1 = np.array([10, 20, 30, 40, 50])<br>
arr2 = np.array([5, 15, 25, 10, 35])

In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])
biger10_arr2 = arr2[arr2>10]
print(biger10_arr2)
select_arr1 = []
for i in arr1:
    for j in biger10_arr2:
        if i > j:
            select_arr1.append(i)
set(select_arr1)

[15 25 35]


{20, 30, 40, 50}

In [4]:
#ex
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])
print([arr2>10])
res = arr1[arr2> 10]# true인것만 나옴
res

[array([False,  True,  True, False,  True])]


array([20, 30, 50])

Task2_0610. 주어진 배열에서 짝수 인덱스에 있는 요소들을 선택하세요.

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
idx = np.argsort(arr)
print(idx)
li = []
for i in idx:
    if i % 2 == 0:
        li.append(i)

print(li)
arr[li]

[0 1 2 3 4 5 6 7]
[0, 2, 4, 6]


array([ 5, 15, 25, 35])

In [5]:
#ex
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
arr[::2]

array([ 5, 15, 25, 35])

Task3_0610. 주어진 배열에서 20보다 작은 요소들의 값을 0으로 변경하세요.

arr = np.array([10, 25, 30, 15, 40, 5])

In [ ]:
arr = np.array([10, 25, 30, 15, 40, 5])
np.where(arr < 20, 0, arr)

array([ 0, 25, 30,  0, 40,  0])

In [6]:
#ex - 더 간단
arr = np.array([10, 25, 30, 15, 40, 5])
arr[arr < 20] = 0
arr


array([ 0, 25, 30,  0, 40,  0])