Task1_0610. 주어진 두 배열 arr1과 arr2에서, arr2의 요소가 10보다 큰 위치의 arr1 요소들을 선택하세요.

arr1 = np.array([10, 20, 30, 40, 50])<br>
arr2 = np.array([5, 15, 25, 10, 35])

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])
biger10_arr2 = arr2[arr2>10]
print(biger10_arr2)
select_arr1 = []
for i in arr1:
    for j in biger10_arr2:
        if i > j:
            select_arr1.append(i)
set(select_arr1)

[15 25 35]


{20, 30, 40, 50}

Task2_0610. 주어진 배열에서 짝수 인덱스에 있는 요소들을 선택하세요.

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

In [9]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
idx = np.argsort(arr)
print(idx)
li = []
for i in idx:
    if i % 2 == 0:
        li.append(i)

print(li)
arr[li]

[0 1 2 3 4 5 6 7]
[0, 2, 4, 6]


array([ 5, 15, 25, 35])

Task3_0610. 주어진 배열에서 20보다 작은 요소들의 값을 0으로 변경하세요.

arr = np.array([10, 25, 30, 15, 40, 5])

In [10]:
arr = np.array([10, 25, 30, 15, 40, 5])
np.where(arr < 20, 0, arr)

array([ 0, 25, 30,  0, 40,  0])