Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [1]:
import numpy as np

D = np.diag([1, 2, 3])
D_inv = np.linalg.inv(D)
print(np.dot(D, D_inv)) #행렬곱 연산 수행시 단위 행렬 나옴 따러서 역행렬 존재하고 역행렬 맞음

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [6]:
#상삼각 행렬은 아래에 0이 있는 형태의 행렬
a_upper = np.triu(np.ones((5,5)))
print(a_upper)
#전치하여 하삼각행렬 만든것과 비교
a_lower_T = a_upper.T
print(a_lower_T)
a_lower = np.tril(np.ones((5,5)))
print(a_lower)
#같은지 확인하기 위해 np.allclose 사용
np.allclose(a_lower_T,a_lower) #True 이므로 같음

[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


True

Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [8]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv)) # 행렬곱 수행이 단위행렬 나오므로 역행렬이 맞음

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3]) #데이터 포인트
레이어 1개 가정, 비활성화 함수도 쓰지 않음
 - 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ(가중치)를 정의.
 - 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [12]:
X = np.array([1, 2, 3]) #데이터 포인트
print(X.shape)
para = np.array([[2,4],[5,2],[2,1]]) #가중치 파라미터
print(para.shape)
y = np.dot(X, para) #행렬곱
print(y, y.shape)


(3,)
(3, 2)
[18 11] (2,)


 Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.
X = np.array([0.5, 1.0, -1.5])
레이어 1개 가정, 비활성화 함수도 쓰지 않음
 - 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
 - 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [13]:
X = np.array([0.5, 1.0, -1.5])
W = np.array([1,2,3])    #가중치 행렬
y = np.dot(X, W)        #행렬곱
print(y)

-2.0


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.(편향벡터 랜덤하게 만들기) =>결과가 Z
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [28]:
X = np.array([1, -2, 3])
W = np.array([-1,-2,3])
b = np.array([4,-5,6])
Z = np.dot(X, W)        #입력벡터와 가중치 행렬곱
Z = np.dot(Z, b)        #위 결과에 편향벡터 행렬곱
print(Z)
def relu(z):
    return np.maximum(0, z)
print(relu(Z))

def sigmoid(z):
    return 1/(1 + np.exp(-z))
print(sigmoid(X))

[ 48 -60  72]
[48  0 72]
[0.73105858 0.11920292 0.95257413]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [18]:
A = np.array([[3,4], [2,1]])        #계수행렬
print(A, A.shape,'\n')
b = np.array([10,5])                #결과벡터
print(b, b.shape,'\n')
A_inv = np.linalg.inv(A)            #계수행렬의 역행렬
print(A_inv, A_inv.shape,'\n')
x = np.dot(A_inv, b)                #역행렬과 결과벡터의 행렬곱
print(x,'\n')
#A와 b의 행렬곱은?
print(np.dot(A,b)) #뭔지 모름 한번 해봄

[[3 4]
 [2 1]] (2, 2) 

[10  5] (2,) 

[[-0.2  0.8]
 [ 0.4 -0.6]] (2, 2) 

[2. 1.] 

[50 25]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [22]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])
new_p = np.dot(T, p)        #새로운 p의 좌표 계산
print(f'New T : {new_p}')
T_inv = np.linalg.inv(T)    #변환 행렬의 역행렬
original_p = np.dot(T_inv, new_p)   #변환행렬의 역행렬과 새로운 좌표를 행렬곱
print(f'Original T : {original_p.astype(int)}')

New T : [2 6]
Original T : [1 2]
