Contents
 - 데이터 구조: Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치(피봇)
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [ ]:
#시리즈 클래스 만들기
#pandas 불로오기
import pandas as pd
#k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr)
print("*" * 10)
print(type(sr))

a    1
b    2
c    3
dtype: int64
**********
<class 'pandas.core.series.Series'>


In [ ]:
#리스트를 시리즈로 변환

list_data = ['2019-08-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-08-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
#리스트를 시리즈로 변환

list_data = ['2019-08-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data, index=list('abcde'))
print(sr, type(sr))

a    2019-08-02
b          3.14
c           ABC
d           100
e          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-08-02' 3.14 'ABC' 100 True]


In [ ]:

#리스트를 시리즈로 변환

list_data = ['2019-08-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-08-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

RangeIndex(start=0, stop=5, step=1)
['2019-08-02' 3.14 'ABC' 100 True]


In [ ]:
#튜플을 시리즈로 변환

tup_data = ('kevin', '2019-07-02', '남', True)

sr = pd.Series(tup_data)
print(sr)
print("*" * 20)
sr = pd.Series(tup_data, index=list('abcd'))
print(sr, type(sr))

0         kevin
1    2019-07-02
2             남
3          True
dtype: object
********************
a         kevin
b    2019-07-02
c             남
d          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
#튜플을 시리즈로 변환

tup_data = ('kevin', '2019-07-02', '남', True)

sr = pd.Series(tup_data)
sr = pd.Series(tup_data, index=['이름', '생년월일','성별','학생여부'])
print(sr, type(sr))

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
sr = [1,2,3,4,5]
sr[1:3]


[2, 3]

In [ ]:
#인덱싱
print(sr[0])
print(sr['이름'])
print(sr[[1,2]])  #리스트내 리스트로 표현, 판다스 시리즈에서만 위치기반 인덱싱을 사용해서 여러 요소를 선택가능
# print(sr[1,2]) 파이썬 기본 인덱싱에서는 하나의 리스트에서 ','구분은 에러 발생, sr[1]같은 형태만

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object


In [ ]:
list('abcde')

In [ ]:
#배열
import numpy as np

s1 = np.arange(11,21,2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
#배열을 생성후 시리즈로 변환하여 아래와 같이 출력하세요.
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

trans = pd.Series(data, index=state, name='population')

print(trans)

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


In [ ]:
#배열을 생성후 시리즈로 변환하여 아래와 같이 출력하세요.
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

trans = pd.Series(data, index=state)
trans.name='population'
trans.index.name = 'state'

print(trans)

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


None과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체형 데이터에서 사용
- np.nan은 부동 소수점으로 취급되며 주로 숫자형 데이터에서 사용
- 연산시 np.nan은 NaN결과를 반환하는 반면 None는 TypeError를 발생시킨다.

In [ ]:
trans.Califonia = np.nan

In [ ]:
trans

Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

obj = pd.Series(data, index=state)
obj.name='population'
obj.index.name = 'state'

In [ ]:
obj.Califonia = np.nan

In [ ]:
null_mask = obj.isnull()
null_mask

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [ ]:
not_null_mask = obj.notnull()
not_null_mask

state
Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool

In [ ]:
filled_series = obj.fillna(0)
filled_series

state
Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
obj.isnull().sum()

1

In [ ]:
dropped_series = obj.dropna()
dropped_series

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [ ]:
dropped_series.isnull().sum()

0

In [ ]:
s2

a    11
b    13
c    15
d    17
e    19
dtype: int64

In [ ]:
type(s2)

pandas.core.series.Series

In [ ]:
#Series -> List
list_from_series = s2.tolist()
list_from_series

[11, 13, 15, 17, 19]

In [ ]:
#Series -> dictionary
dict_from_series = s2.to_dict()
dict_from_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

In [ ]:
#Series -> dataframe
df_from_series = s2.to_frame(name='Value')#컬럼 이름이 Value
print(df_from_series, type(df_from_series))

   Value
a     11
b     13
c     15
d     17
e     19 <class 'pandas.core.frame.DataFrame'>


Q. 아래 시리즈에서 null값을 2개 입력후 그 값을 0으로 대체후 null값 여부를 확인한 후 출력하세요.

In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s[0] = np.nan
s[2] = np.nan
filled_series = s.fillna(0)
print(filled_series)
filled_series.isnull().sum()
print(filled_series)

x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64
x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64


In [ ]:
#ex
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s[0] = np.nan
s[2] = np.nan
print('null갯수: ', s.isna().sum())
filled_series = s.fillna(0)
print('null갯수: ', filled_series.isna().sum())
print(filled_series)

null갯수:  2
null갯수:  0
x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.


In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

s = pd.Series(data_list)
print(s, type(s))
s = s + 10
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'>
0    11
1    12
2    13
3    14
4    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [ ]:
list1 = [10, 20, 30, 40, 50]
s = pd.Series(list1, index=list('abcde'))
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
#ex
data= [10, 20, 30, 40, 50]
index = ['a', 'c','b','d','e']

s = pd.Series(data, index=index)
s_sorted = s.sort_index()

print(s)
print(s_sorted)

a    10
c    20
b    30
d    40
e    50
dtype: int64
a    10
b    30
c    20
d    40
e    50
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

s = pd.Series(data, index=index)
print(s)
print(s[1], s['b'])
print(s[3])

a    1
b    2
c    3
d    4
e    5
dtype: int64
2 2
4


In [ ]:
#ex
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

s = pd.Series(data, index=index)
print(s)

selected_elements = s[['b', 'd']]
print(selected_elements)

a    1
b    2
c    3
d    4
e    5
dtype: int64
b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [ ]:
#배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns= ['pd','sales','inv'])
print(df, type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [ ]:
print(df.pd, type(df.pd)) #하나의 열은 시리즈 객체

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
df = pd.DataFrame(data, columns= ['pd','sales','inv'] )  #인덱스 없으면 자동으로 숫자 인덱스 부여
df

pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  -  끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 양 끝점 포함: 슬라이싱 시 끝점을 포함.

In [ ]:
import pandas as pd

data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data)
print(df,'\n')
print(df.iloc[0,1])
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


In [ ]:
import pandas as pd

data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data, index=list('abcd'))
print(df,'\n')
print(df.loc['a', 'B'])
print(df.loc['a':'b', 'A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5
   A  B
a  1  5
b  2  6


In [ ]:
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns= ['pd','sales','inv'])
print(df, type(df))


[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [ ]:
#pandas indexing
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [ ]:
print(df.iloc[1,:], '\n')
print(df.loc['d2',:])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [ ]:
#Q. 107선택
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns= ['pd','sales','inv'])
print(df, type(df))
print(df.iloc[1,2])
print(df.loc['d2','inv'])

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>
107
107


In [ ]:
df.loc['d3'] = 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [ ]:
df.loc['d4'] = 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [ ]:
df.iloc[4] = 0 #iloc로는 확대 안됨
df

IndexError: iloc cannot enlarge its target object

In [ ]:
df.loc[:,'profit'] = 10  #컬럼 추가후 값 넣기
df

pd  sales  inv  profit
d1  112    115  100      10
d2  103    103  107      10
d3    0      0    0      10
d4    0      0    0      10

파이썬 random()함수

In [ ]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.9336249570114484 

4 

19.11288281267059 

2 

5 

[1, 3, 4] 

[1, 2, 4, 5, 3]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

7 

[8 8 1 6 7 7 8 1 5 9] 

[18 19 14 13 10 13 15 10 12 13] 

[[18 11 13 13 13]
 [17 10 11 19 19]
 [10 14 17 13 12]]


In [ ]:
np.arange(1, 1001)

In [ ]:
#id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1, 1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11, size=1000)
r1 = pd.Series(region)
df = pd.concat([i1,g1,a1,r1], axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'},inplace=True)
df.head()

id  gender  age  region
0   1       1   17       6
1   2       1   76       8
2   3       1  100       6
3   4       0   10       4
4   5       0   74       4

In [ ]:
df.drop([0], axis=0, inplace=True) #두번 하면 없는 인덱스
df.head()

KeyError: '[0] not found in axis'

- at:라벨기반 인덱싱을 사용. 단일값을 접근할 때 loc접근자보다 빠르다.

- 여러 값을 동시에 접근하려면 loc접근자를 사용

In [ ]:
df.loc[5, 'id']

6

In [ ]:
df.at[5, 'id']

6

In [ ]:
df1 = df.drop(df.at[5,'id'])
df1.head(7)

id  gender  age  region
1   2       1   76       8
2   3       1  100       6
3   4       0   10       4
4   5       0   74       4
5   6       1   31       5
7   8       0   21       2
8   9       0   84       4

In [ ]:
#기존 데이터프레임 복사
df1 = df.copy()
df1.head()

id  gender  age  region
1   2       1   76       8
2   3       1  100       6
3   4       0   10       4
4   5       0   74       4
5   6       1   31       5

In [ ]:
np.random.seed(0)
a = np.random.randint(1,5, size=(10,5))
print(a,type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [ ]:
#2차원 리스트를 데이터프레임으로 변환
list1 = a.tolist()

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1.head())

   c1  c2  c3  c4  c5
0   1   4   2   1   4
1   4   4   4   2   4
2   2   3   1   4   3
3   1   1   1   3   2
4   3   4   4   3   1


In [ ]:
#데이터 프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar, type(ar))
print()
li = ar.tolist()
print(li, type(li))
print()
dict = df1.to_dict('list')  #'list'를 지정
print(dict, type(dict))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>


#5월 28일

In [4]:
import numpy as np
import pandas as pd

df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})
df5[['Name','City']]  #컬럼은 리스트로 인덱싱 가능

Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix

In [5]:
#file 생성
import pandas as pd
file_data = pd.DataFrame({
    'col1':[1,2,3,4,5,6],
    'col2':['a','a','b','b','c','c']
})
print(file_data)

   col1 col2
0     1    a
1     2    a
2     3    b
3     4    b
4     5    c
5     6    c


In [7]:
file_data.to_csv('file_data.csv', index=None)

In [8]:
!ls

file_data.csv  sample_data


In [10]:
!cat file_data.csv

col1,col2
1,a
2,a
3,b
4,b
5,c
6,c


In [13]:
file_data = pd.read_csv('file_data.csv')
print(file_data,'\n',type(file_data))

   col1 col2
0     1    a
1     2    a
2     3    b
3     4    b
4     5    c
5     6    c 
 <class 'pandas.core.frame.DataFrame'>


In [14]:
import pandas as pd
file_data = pd.DataFrame({
    'col1':[1,2,3,4,5,6],
    'col2':['a','a','b','b','c','c']
})
print(file_data)
file_data.to_csv('file_data.csv') #None안들어갈경우
file_data = pd.read_csv('file_data.csv')
print(file_data,'\n',type(file_data))

   col1 col2
0     1    a
1     2    a
2     3    b
3     4    b
4     5    c
5     6    c
   Unnamed: 0  col1 col2
0           0     1    a
1           1     2    a
2           2     3    b
3           3     4    b
4           4     5    c
5           5     6    c 
 <class 'pandas.core.frame.DataFrame'>


In [15]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1)
print()
print(df_2)

   col1 col2
0     1    A
1     2    B
2     3    C

   col1 col2
0     4    D
1     5    E
2     6    F


In [16]:
#Q.df1과 df2를 행방향과 열방향으로 병합하여 출력하세요.
df_3 = pd.concat([df_1, df_2], axis=1)
df_4 = pd.concat([df_1, df_2])
print(df_3)
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F
   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [17]:
# 데이터프레임 생성(8행 5열)
import numpy as np
import pandas as pd

np.random.seed(3)
data = np.random.randint(50,100,size=(8,5))

df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  74  53  58  50
1  71  69  60  93  91
2  60  71  88  82  70
3  94  79  89  64  76
4  67  76  72  52  52
5  51  76  55  90  96
6  83  79  92  74  57
7  93  83  65  98  87

In [18]:
#열이름과 행이름 변경
columns={'a':'국어','b':'영어','c':'수학','d':'과학','e':'음악'}
index={0:'a',1:'b',2:'c',3:'d',4:'e',5:'f',6:'g',7:'h'}

df.rename(columns=columns, index=index, inplace=True)
df

국어  영어  수학  과학  음악
a  92  74  53  58  50
b  71  69  60  93  91
c  60  71  88  82  70
d  94  79  89  64  76
e  67  76  72  52  52
f  51  76  55  90  96
g  83  79  92  74  57
h  93  83  65  98  87

In [20]:
# 데이터프레임 생성
import numpy as np
import pandas as pd
np.random.seed(0)

data = np.random.randint(80,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [23]:
df1 = df.copy()
df1['index'] = list('가나다라마')
df2 = df1.set_index('index')
df2

a   b   c   d   e
index                    
가      92  95  80  83  83
나      87  89  99  98  84
다      86  92  81  86  87
라      94  97  85  93  88
마      89  99  96  99  85

In [24]:
df21 = df2.drop('e', axis=1) #axis=1 열방향
df21

a   b   c   d
index                
가      92  95  80  83
나      87  89  99  98
다      86  92  81  86
라      94  97  85  93
마      89  99  96  99

In [25]:
df3 = df2.reset_index()
df3

index   a   b   c   d   e
0     가  92  95  80  83  83
1     나  87  89  99  98  84
2     다  86  92  81  86  87
3     라  94  97  85  93  88
4     마  89  99  96  99  85

In [26]:
df22 = df3.set_index('index')
df22

a   b   c   d   e
index                    
가      92  95  80  83  83
나      87  89  99  98  84
다      86  92  81  86  87
라      94  97  85  93  88
마      89  99  96  99  85

In [27]:
df22.index.name = None
df22

a   b   c   d   e
가  92  95  80  83  83
나  87  89  99  98  84
다  86  92  81  86  87
라  94  97  85  93  88
마  89  99  96  99  85

In [34]:
# 딕셔서리를 정의
dict_data = {'a':[1,2,3,4,5], 'b':[4,5,6,7,8], 'c':[7,8,9,10,11], 'd':[10,11,12,13,14], 'e':[13,14,15,16,17]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0','r1','r2','r3','r4'])
df

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [35]:
#Q.df에 r5,r6 2개의 행을 추가하고 값은 0을 적용하여 출력하세요
df.loc['r5'] = 0
df.loc['r6'] = 0
df

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17
r5  0  0   0   0   0
r6  0  0   0   0   0

In [36]:
new_index = ['r0','r1','r2','r3','r4','r5','r6','r7','r8']
df5 = df.reindex(new_index, fill_value=0)
df5

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17
r5  0  0   0   0   0
r6  0  0   0   0   0
r7  0  0   0   0   0
r8  0  0   0   0   0

In [37]:
new_index = ['r0','r1','r2','r3','r4']
df1 = df5.reindex(new_index)
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [38]:
df1 = df5.drop(df5.index[5:9])
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [39]:
#r5~r8삭제후 출력
df1 = df5.drop(['r5','r6','r7','r8'], axis=0)
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [40]:
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [41]:
#인덱스 기준 정렬
df1_s = df1.sort_index(ascending=False)
df1_s

a  b   c   d   e
r4  5  8  11  14  17
r3  4  7  10  13  16
r2  3  6   9  12  15
r1  2  5   8  11  14
r0  1  4   7  10  13

In [42]:
#value 기준 정렬
df1_c = df1.sort_values(by='c', ascending=False)
df1_c

a  b   c   d   e
r4  5  8  11  14  17
r3  4  7  10  13  16
r2  3  6   9  12  15
r1  2  5   8  11  14
r0  1  4   7  10  13

In [43]:
#전치
df1_t = df1.transpose()
#df1_t = df1.T
df1_t

r0  r1  r2  r3  r4
a   1   2   3   4   5
b   4   5   6   7   8
c   7   8   9  10  11
d  10  11  12  13  14
e  13  14  15  16  17

In [44]:
df1 = df1_t.T
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

Q. df1으로 데이터프레임을 생성한 후 set_index를 사용하여 ID를 인덱스 설정한 데이터프레임을 출력하세요.

In [66]:
df1 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

df1
df1 = df1.set_index('ID')
print(df1)
df1.info()

        Name  Age
ID               
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 101 to 104
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes


Q. df2에 대해서 다음을 수행하세요.
- set_index를 사용하여 인덱스를 설정.
- reset_index를 사용하여 인덱스를 리셋.

In [49]:
df2 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})
df2
df2_set = df2.set_index('Age')
print(df2_set)
df2 = df2_set.reset_index()
df2

      ID     Name
Age              
24   101    Alice
27   102      Bob
22   103  Charlie
32   104    David


Age   ID     Name
0   24  101    Alice
1   27  102      Bob
2   22  103  Charlie
3   32  104    David

Q. df3에 대해서 reindex를 사용하여 인덱스를 변경하여 출력하세요.

In [56]:
df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}, index=[101, 102, 103, 104])

df3
new_index = [101, 102, 103]
df3_reidx = df3.reindex(new_index)
df3_reidx

Name  Age
101    Alice   24
102      Bob   27
103  Charlie   22

In [71]:
#ex
df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}, index=[101, 102, 103, 104])
new_index = [101, 102, 105,106]
df3_reidx = df3.reindex(new_index)
df3_reidx


Name   Age
101  Alice  24.0
102    Bob  27.0
105    NaN   NaN
106    NaN   NaN

Q. df4에 대해서 reindex를 사용하여 인덱스를 변경하고 결측치를 0으로 채운 데이터프레임을 출력하세요.

In [55]:
df4 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22]
}, index=[0, 1, 2])

print("기존 인덱스:\n", df4)

new_index = [0, 1, 2,3,4,5]
df4_reidx = df4.reindex(new_index, fill_value=0)
df4_reidx

기존 인덱스:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22


Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3        0    0
4        0    0
5        0    0

Q. df5에서 reindex를 사용하여 특정 날짜 범위로 인덱스를 재설정하여 출력하세요.

In [59]:
dates = pd.date_range('2024-01-01', periods=4, freq='D')
df5 = pd.DataFrame({
    'Value': [10, 20, 30, 40]
}, index=dates)
print(df5)
new_index = ['2024-01-01','2024-01-02']
df5_reidx = df5.reindex(new_index, fill_value=0)
df5_reidx

            Value
2024-01-01     10
2024-01-02     20
2024-01-03     30
2024-01-04     40


Value
2024-01-01     10
2024-01-02     20

In [73]:
#ex
dates = pd.date_range('2024-01-01', periods=4, freq='D')
df5 = pd.DataFrame({
    'Value': [10, 20, 30, 40]
}, index=dates)

new_dates = pd.date_range('2024-01-01', periods=6, freq='D')
df_reindexed = df5.reindex(new_dates, fill_value=10)
print(df_reindexed)

            Value
2024-01-01     10
2024-01-02     20
2024-01-03     30
2024-01-04     40
2024-01-05     10
2024-01-06     10


Q. 데이터프레임 df6를 전치하고, 전치된 데이터프레임을 정리하여 연도별 판매량 데이터를 제품별로 나열하여 출력하세요.

In [63]:
data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)
print(df6)
df6_t = df6.T
print(df6_t)
df6_t.info()

   Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500
              0     1     2
Year       2020  2021  2022
Product_A   500   600   700
Product_B   400   500   600
Product_C   300   400   500
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Year to Product_C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       4 non-null      object
 1   1       4 non-null      object
 2   2       4 non-null      object
dtypes: object(3)
memory usage: 300.0+ bytes


In [65]:
data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)
print(df6)
df6 = df6.set_index('Year')
print(df6)
df6_t = df6.T
print(df6_t)
df6_t.info()

   Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500
      Product_A  Product_B  Product_C
Year                                 
2020        500        400        300
2021        600        500        400
2022        700        600        500
Year       2020  2021  2022
Product_A   500   600   700
Product_B   400   500   600
Product_C   300   400   500
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Product_A to Product_C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2020    3 non-null      int64
 1   2021    3 non-null      int64
 2   2022    3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes


In [76]:
#ex

data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)
print(df6)
df6 = df6.set_index('Year')
print(df6)
df6_t = df6.T

df6_t.reset_index(inplace=True)
df6_t.rename(columns={'index':'Product'},inplace=True)
df6_t

   Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500
      Product_A  Product_B  Product_C
Year                                 
2020        500        400        300
2021        600        500        400
2022        700        600        500


Year    Product  2020  2021  2022
0     Product_A   500   600   700
1     Product_B   400   500   600
2     Product_C   300   400   500

In [68]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice", "Bob"],
    "Subject": ["Math", "Math", "English", "English"],
    "Score": [85, 79, 92, 85]
})
print(df)
# 피벗 테이블 생성
pivot_df = df.pivot(index='Name', columns='Subject', values='Score')
print(pivot_df)
pivot_df2 = df.pivot(index='Subject', columns='Name', values='Score')
print(pivot_df2)

    Name  Subject  Score
0  Alice     Math     85
1    Bob     Math     79
2  Alice  English     92
3    Bob  English     85
Subject  English  Math
Name                  
Alice         92    85
Bob           85    79
Name     Alice  Bob
Subject            
English     92   85
Math        85   79


In [69]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 79, 88],
    "English": [92, 85, 89]
})
print(df)
# 데이터프레임 전치
transposed_df = df.transpose()
print(transposed_df)


      Name  Math  English
0    Alice    85       92
1      Bob    79       85
2  Charlie    88       89
             0    1        2
Name     Alice  Bob  Charlie
Math        85   79       88
English     92   85       89
