Contents
 - 데이터 구조: Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치(피봇)
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [5]:
#시리즈 클래스 만들기
#pandas 불로오기
import pandas as pd
#k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr)
print("*" * 10)
print(type(sr))

a    1
b    2
c    3
dtype: int64
**********
<class 'pandas.core.series.Series'>


In [6]:
#리스트를 시리즈로 변환

list_data = ['2019-08-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-08-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [7]:
#리스트를 시리즈로 변환

list_data = ['2019-08-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data, index=list('abcde'))
print(sr, type(sr))

a    2019-08-02
b          3.14
c           ABC
d           100
e          True
dtype: object <class 'pandas.core.series.Series'>


In [8]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-08-02' 3.14 'ABC' 100 True]


In [10]:

#리스트를 시리즈로 변환

list_data = ['2019-08-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-08-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [12]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

RangeIndex(start=0, stop=5, step=1)
['2019-08-02' 3.14 'ABC' 100 True]


In [17]:
#튜플을 시리즈로 변환

tup_data = ('kevin', '2019-07-02', '남', True)

sr = pd.Series(tup_data)
print(sr)
print("*" * 20)
sr = pd.Series(tup_data, index=list('abcd'))
print(sr, type(sr))

0         kevin
1    2019-07-02
2             남
3          True
dtype: object
********************
a         kevin
b    2019-07-02
c             남
d          True
dtype: object <class 'pandas.core.series.Series'>


In [18]:
#튜플을 시리즈로 변환

tup_data = ('kevin', '2019-07-02', '남', True)

sr = pd.Series(tup_data)
sr = pd.Series(tup_data, index=['이름', '생년월일','성별','학생여부'])
print(sr, type(sr))

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object <class 'pandas.core.series.Series'>


In [29]:
sr = [1,2,3,4,5]
sr[1:3]


[2, 3]

In [21]:
#인덱싱
print(sr[0])
print(sr['이름'])
print(sr[[1,2]])  #리스트내 리스트로 표현, 판다스 시리즈에서만 위치기반 인덱싱을 사용해서 여러 요소를 선택가능
# print(sr[1,2]) 파이썬 기본 인덱싱에서는 하나의 리스트에서 ','구분은 에러 발생, sr[1]같은 형태만

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object


In [ ]:
list('abcde')

In [22]:
#배열
import numpy as np

s1 = np.arange(11,21,2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [27]:
#배열을 생성후 시리즈로 변환하여 아래와 같이 출력하세요.
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

trans = pd.Series(data, index=state, name='population')

print(trans)

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


In [26]:
#배열을 생성후 시리즈로 변환하여 아래와 같이 출력하세요.
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

trans = pd.Series(data, index=state)
trans.name='population'
trans.index.name = 'state'

print(trans)

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


None과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체형 데이터에서 사용
- np.nan은 부동 소수점으로 취급되며 주로 숫자형 데이터에서 사용
- 연산시 np.nan은 NaN결과를 반환하는 반면 None는 TypeError를 발생시킨다.

In [30]:
trans.Califonia = np.nan

In [31]:
trans

Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [32]:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

obj = pd.Series(data, index=state)
obj.name='population'
obj.index.name = 'state'

In [34]:
obj.Califonia = np.nan

In [35]:
null_mask = obj.isnull()
null_mask

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [36]:
not_null_mask = obj.notnull()
not_null_mask

state
Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool

In [37]:
filled_series = obj.fillna(0)
filled_series

state
Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [38]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [39]:
obj.isnull().sum()

1

In [40]:
dropped_series = obj.dropna()
dropped_series

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [41]:
dropped_series.isnull().sum()

0

In [42]:
s2

a    11
b    13
c    15
d    17
e    19
dtype: int64

In [43]:
type(s2)

pandas.core.series.Series

In [44]:
#Series -> List
list_from_series = s2.tolist()
list_from_series

[11, 13, 15, 17, 19]

In [45]:
#Series -> dictionary
dict_from_series = s2.to_dict()
dict_from_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

In [48]:
#Series -> dataframe
df_from_series = s2.to_frame(name='Value')#컬럼 이름이 Value
print(df_from_series, type(df_from_series))

   Value
a     11
b     13
c     15
d     17
e     19 <class 'pandas.core.frame.DataFrame'>


Q. 아래 시리즈에서 null값을 2개 입력후 그 값을 0으로 대체후 null값 여부를 확인한 후 출력하세요.

In [62]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s[0] = np.nan
s[2] = np.nan
filled_series = s.fillna(0)
print(filled_series)
filled_series.isnull().sum()
print(filled_series)

x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64
x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64


In [69]:
#ex
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s[0] = np.nan
s[2] = np.nan
print('null갯수: ', s.isna().sum())
filled_series = s.fillna(0)
print('null갯수: ', filled_series.isna().sum())
print(filled_series)

null갯수:  2
null갯수:  0
x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.


In [70]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

s = pd.Series(data_list)
print(s, type(s))
s = s + 10
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'>
0    11
1    12
2    13
3    14
4    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [56]:
list1 = [10, 20, 30, 40, 50]
s = pd.Series(list1, index=list('abcde'))
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [71]:
#ex
data= [10, 20, 30, 40, 50]
index = ['a', 'c','b','d','e']

s = pd.Series(data, index=index)
s_sorted = s.sort_index()

print(s)
print(s_sorted)

a    10
c    20
b    30
d    40
e    50
dtype: int64
a    10
b    30
c    20
d    40
e    50
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [61]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

s = pd.Series(data, index=index)
print(s)
print(s[1], s['b'])
print(s[3])

a    1
b    2
c    3
d    4
e    5
dtype: int64
2 2
4


In [73]:
#ex
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

s = pd.Series(data, index=index)
print(s)

selected_elements = s[['b', 'd']]
print(selected_elements)

a    1
b    2
c    3
d    4
e    5
dtype: int64
b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [75]:
#배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns= ['pd','sales','inv'])
print(df, type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [77]:
print(df.pd, type(df.pd)) #하나의 열은 시리즈 객체

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [79]:
df = pd.DataFrame(data, columns= ['pd','sales','inv'] )  #인덱스 없으면 자동으로 숫자 인덱스 부여
df

pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  -  끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 양 끝점 포함: 슬라이싱 시 끝점을 포함.

In [80]:
import pandas as pd

data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data)
print(df,'\n')
print(df.iloc[0,1])
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


In [81]:
import pandas as pd

data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data, index=list('abcd'))
print(df,'\n')
print(df.loc['a', 'B'])
print(df.loc['a':'b', 'A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5
   A  B
a  1  5
b  2  6


In [82]:
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns= ['pd','sales','inv'])
print(df, type(df))


[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [83]:
#pandas indexing
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [84]:
print(df.iloc[1,:], '\n')
print(df.loc['d2',:])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [88]:
#Q. 107선택
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns= ['pd','sales','inv'])
print(df, type(df))
print(df.iloc[1,2])
print(df.loc['d2','inv'])

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>
107
107


In [89]:
df.loc['d3'] = 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [90]:
df.loc['d4'] = 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [91]:
df.iloc[4] = 0 #iloc로는 확대 안됨
df

IndexError: iloc cannot enlarge its target object

In [92]:
df.loc[:,'profit'] = 10  #컬럼 추가후 값 넣기
df

pd  sales  inv  profit
d1  112    115  100      10
d2  103    103  107      10
d3    0      0    0      10
d4    0      0    0      10

파이썬 random()함수

In [93]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.9336249570114484 

4 

19.11288281267059 

2 

5 

[1, 3, 4] 

[1, 2, 4, 5, 3]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [94]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

7 

[8 8 1 6 7 7 8 1 5 9] 

[18 19 14 13 10 13 15 10 12 13] 

[[18 11 13 13 13]
 [17 10 11 19 19]
 [10 14 17 13 12]]


In [95]:
np.arange(1, 1001)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [97]:
#id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1, 1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11, size=1000)
r1 = pd.Series(region)
df = pd.concat([i1,g1,a1,r1], axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'},inplace=True)
df.head()

id  gender  age  region
0   1       1   17       6
1   2       1   76       8
2   3       1  100       6
3   4       0   10       4
4   5       0   74       4

In [99]:
df.drop([0], axis=0, inplace=True) #두번 하면 없는 인덱스
df.head()

KeyError: '[0] not found in axis'

- at:라벨기반 인덱싱을 사용. 단일값을 접근할 때 loc접근자보다 빠르다.

- 여러 값을 동시에 접근하려면 loc접근자를 사용

In [101]:
df.loc[5, 'id']

6

In [100]:
df.at[5, 'id']

6

In [102]:
df1 = df.drop(df.at[5,'id'])
df1.head(7)

id  gender  age  region
1   2       1   76       8
2   3       1  100       6
3   4       0   10       4
4   5       0   74       4
5   6       1   31       5
7   8       0   21       2
8   9       0   84       4

In [103]:
#기존 데이터프레임 복사
df1 = df.copy()
df1.head()

id  gender  age  region
1   2       1   76       8
2   3       1  100       6
3   4       0   10       4
4   5       0   74       4
5   6       1   31       5

In [104]:
np.random.seed(0)
a = np.random.randint(1,5, size=(10,5))
print(a,type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [105]:
#2차원 리스트를 데이터프레임으로 변환
list1 = a.tolist()

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1.head())

   c1  c2  c3  c4  c5
0   1   4   2   1   4
1   4   4   4   2   4
2   2   3   1   4   3
3   1   1   1   3   2
4   3   4   4   3   1


In [106]:
#데이터 프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar, type(ar))
print()
li = ar.tolist()
print(li, type(li))
print()
dict = df1.to_dict('list')  #'list'를 지정
print(dict, type(dict))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>
