## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

## 기초 **연산**

In [2]:
import pandas as pd

st1 = pd.Series({'국어':100 ,'영어':80 , '수학':90})
st2 = pd.Series({'국어':90 ,'영어':80 , '수학':80})

print(st1, '\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

국어    90
영어    80
수학    80
dtype: int64


In [3]:
pd.DataFrame(st1+st2)

0
국어  190
영어  160
수학  170

In [5]:
#두 학생의 과목별 점수로 사칙연산 수행
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

df = pd.concat([add,sub,mul,div],axis=1)
print(df)

      0   1     2     3
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12


In [6]:
df = pd.concat([add,sub,mul,div],axis=1)
df.columns = ['덧셈','뺄셈','곱셈','나눗셈']
df

덧셈  뺄셈    곱셈   나눗셈
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12

In [7]:
print(add,type(add))    #시리즈

국어    190
영어    160
수학    170
dtype: int64 <class 'pandas.core.series.Series'>


In [8]:
result = pd.DataFrame([add,sub,mul,div])               #데이터프레임에 리스트로 넣으면 행으로 들어감
result

국어      영어       수학
0   190.00   160.0   170.00
1    10.00     0.0    10.00
2  9000.00  6400.0  7200.00
3     1.11     1.0     1.12

In [9]:
result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])               #인덱스로 넣줘야함
result

국어      영어       수학
덧셈    190.00   160.0   170.00
뺄셈     10.00     0.0    10.00
곱셈   9000.00  6400.0  7200.00
나눗셈     1.11     1.0     1.12

In [11]:
import numpy as np

st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [22]:
#Q.null값을 0으로 변경하여 결과를 출력하세요
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

ad = st1.add(st2, fill_value=0)
su = st1.sub(st2, fill_value=0)
mu = st1.mul(st2, fill_value=0)
di = st1.div(st2, fill_value=0)
result = pd.DataFrame([ad,su,mu,di],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [24]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

print(df1,'\n')
print(df2)


     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [25]:
df2.loc[1,'b'] = np.nan
print(df1,'\n')
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [26]:
df1 + df2       #df1 때문에 가장 자리에 nan 생김

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [27]:
#계산인자를 뒤집어 계산
df1.rdiv(1) #해당 숫자가 분자로 들어가서 계산


a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [28]:
print(df1)
df1.rsub(1)     #안에 숫자 - 항목

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [29]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [31]:
print(df1)
df1.rmul(10)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b      c      d
0   0.0  10.0   20.0   30.0
1  40.0  50.0   60.0   70.0
2  80.0  90.0  100.0  110.0

In [35]:
#배열의 연산
arr = np.arange(12.).reshape((3,4))
print(arr,'\n')
print(arr[0])       #배열의 인덱싱


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [36]:
#broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [37]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [38]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [39]:
frame - series  #데이터프레임도 브로드캐스팅됨

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [43]:
a = np.arange(6).reshape(1,6)
a


array([[0, 1, 2, 3, 4, 5]])

In [41]:
a = np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [ ]:
import pandas as pd
import seaborn as sns
titanic = sns.