In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
import pandas as pd

# FutureWarning 경고 메시지를 무시하도록 설정
warnings.simplefilter(action="ignore", category=FutureWarning)

Task1_0723. 'Breast Cancer Wisconsin (Diagnostic) Data Set'을 사용하여 이진 분류 문제를 해결하고, 평가 지표(정확도, 정밀도, 재현율, F1 스코어, ROC AUC)를 계산하세요.

In [33]:
# 데이터 로드
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
import pandas as pd

data = load_breast_cancer()
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [9]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [13]:
data.filename

'breast_cancer.csv'

In [10]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [17]:
print(type(data))

<class 'sklearn.utils._bunch.Bunch'>


In [19]:
# sklearn.utils._bunch.Bunch to dataframe
df = data.data

In [34]:
X_breast_df = data.data
X_breast_df

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [35]:
y_breast_df = data.target
y_breast_df

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_breast_df, y_breast_df, test_size=0.2, random_state=11)

In [37]:
lr_clf = LogisticRegression(max_iter=2000, solver='lbfgs', random_state=42)
lr_clf.fit(X_train, y_train)
pred = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:,1]
print(pred_proba)

[1.28739761e-06 1.73724220e-10 2.65886611e-08 5.11413241e-08
 1.96612128e-10 9.94329589e-01 7.73452727e-01 9.94182705e-01
 9.99867840e-01 9.98400220e-01 9.99800516e-01 4.01351674e-01
 9.17641306e-01 9.99947500e-01 9.99997288e-01 9.99379605e-01
 8.71954516e-02 7.84119287e-01 9.98495492e-01 4.75934722e-10
 1.48696550e-02 9.99910329e-01 9.99365139e-01 9.99960976e-01
 9.75158964e-01 9.99743895e-01 9.99989537e-01 8.22200327e-01
 9.95787986e-01 9.54039401e-01 9.96249179e-01 9.99242780e-01
 9.99769876e-01 9.99832335e-01 8.73930238e-01 9.99407171e-01
 9.56180741e-01 9.93971572e-01 9.68512581e-01 9.07115309e-01
 9.99636671e-01 3.65165419e-03 9.99901652e-01 9.99981451e-01
 9.52908614e-01 9.99888002e-01 1.58725609e-07 9.80315789e-01
 2.10254850e-05 9.89320620e-07 9.99971867e-01 9.99384356e-01
 1.11262540e-05 9.99403171e-01 9.16559907e-01 9.89668920e-01
 7.56879330e-03 9.98896574e-01 9.49728567e-01 9.99921076e-01
 5.63386171e-03 6.84517008e-03 9.88710788e-01 9.91196059e-01
 3.58272217e-05 9.999533

d:\kdt_240424\workspace\M5_ML\venv\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [38]:
def get_clf_eval(y_test, pred, pred_proba):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차행렬')
    print(confusion)
    print(
        f"정확도 : {accuracy:.4f}, 정밀도 : {precision:.4f}, 재현율 : {recall:.4f}, F1 : {f1:.4f}, AUC : {roc_auc:.4f}"
    )

In [39]:
get_clf_eval(y_test, pred, pred_proba)

오차행렬
[[34  4]
 [ 2 74]]
정확도 : 0.9474, 정밀도 : 0.9487, 재현율 : 0.9737, F1 : 0.9610, AUC : 0.9948


Task2_0723.
가상의 데이터셋을 생성하고, 이를 사용하여 다중 클래스 분류 모델을 훈련시킨 후 평가 지표를 계산하세요. 평가 지표는 정확도, 정밀도, 재현율, F1 스코어, ROC AUC입니다.

- n_samples=1500: 데이터셋에 포함될 샘플의 수를 1500개로 지정합니다.
- n_features=20: 각 샘플이 가질 특성(feature)의 수를 20개로 지정합니다.
- n_classes=5: 타겟 라벨의 클래스 수를 5개로 지정합니다.
- n_informative=15: 20개의 특성 중 15개는 타겟 라벨과 관련된 유용한 정보를 포함하도록 지정합니다. 나머지 5개의 특성은 유용하지 않거나 무작위로 생성된 특성입니다.
- random_state=42: 재현성을 위해 난수 생성 seed를 설정합니다.

In [47]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.preprocessing import label_binarize

# 데이터 생성 (5개의 클래스)
X, y = make_classification(n_samples=1500, n_features=20, n_classes=5, n_informative=15, random_state=42)
print(X.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, y_train)

pred = model.predict(X_test)
pred_proba = model.predict_proba(X_test)
y_test_binarize = label_binarize(y_test, classes=[0,1,2,3,4])
roc_auc_ovr = roc_auc_score(y_test_binarize, pred_proba, multi_class='ovr')
print(roc_auc_ovr)

(1500, 20)
0.8743419315143963


In [56]:
def get_randomforest_eval(y_test, pred, pred_proba):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred, average='weighted')
    recall = recall_score(y_test, pred, average='weighted')
    f1 = f1_score(y_test, pred, average='weighted')
    y_test_binarize = label_binarize(y_test, classes=[0,1,2,3,4])

    roc_auc_ovr = roc_auc_score(y_test_binarize, pred_proba, multi_class='ovr')
    print("오차행렬")
    print(confusion)
    print(
        f"정확도 : {accuracy:.4f}, 정밀도 : {precision:.4f}, 재현율 : {recall:.4f}, F1 : {f1:.4f}, AUC : {roc_auc_ovr:.4f}"
    )

In [57]:
get_randomforest_eval(y_test, pred, pred_proba)

오차행렬
[[146  23  31  22  23]
 [  9 172  24   3  28]
 [ 14  42 158  10  15]
 [ 40  35  32 101  39]
 [ 21  29  15   3 165]]
정확도 : 0.6183, 정밀도 : 0.6312, 재현율 : 0.6183, F1 : 0.6127, AUC : 0.8743


Task3_0723. 주어진 코드를 수정해서 모델의 성능을 개선하세요.

In [60]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. 데이터 로드
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "income",
]
data = pd.read_csv(
    url, header=None, names=columns, na_values=" ?", skipinitialspace=True
)

# 2. 결측치 처리
# 수치형 변수의 결측치를 중앙값으로 대체
numeric_features = data.select_dtypes(include=[np.number]).columns.tolist()
imputer_numeric = SimpleImputer(strategy="median")
data[numeric_features] = imputer_numeric.fit_transform(data[numeric_features])

# 범주형 변수의 결측치를 최빈값으로 대체
categorical_features = data.select_dtypes(include=[object]).columns.tolist()
categorical_features.remove("income")
imputer_categorical = SimpleImputer(strategy="most_frequent")
data[categorical_features] = imputer_categorical.fit_transform(
    data[categorical_features]
)


# 3. 이상치 제거 (여기서는 'capital-gain'과 'capital-loss'에서 극단적인 값들을 이상치로 가정)
def replace_outliers_with_median(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    median = df[column].median()
    df[column] = np.where(
        (df[column] < lower_bound) | (df[column] > upper_bound), median, df[column]
    )
    return df


for col in numeric_features:
    data = replace_outliers_with_median(data, col)

# 4. 파생변수 작성
data["capital_diff"] = data["capital-gain"] - data["capital-loss"]

# 5. 범주형 변수 인코딩
categorical_features = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
]
# encoder = OneHotEncoder(drop="first", sparse=False)
# encoded_categorical_data = encoder.fit_transform(data[categorical_features])
# encoded_categorical_df = pd.DataFrame(
#     encoded_categorical_data,
#     columns=encoder.get_feature_names_out(categorical_features),
# )

data = pd.get_dummies(data, columns=categorical_features, drop_first=True)

# 원래 데이터프레임에서 범주형 열을 제거하고 인코딩된 데이터프레임을 병합
# data = data.drop(columns=categorical_features)
# data = pd.concat([data, encoded_categorical_df], axis=1)

# 6. 변수 선택 및 데이터 분리
# 'income' 변수를 0과 1로 변환
# data["income"] = data["income"].apply(lambda x: 1 if x.strip() == ">50K" else 0)
X = data.drop("income", axis=1)
y = data["income"]

# 7. 데이터 표준화
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 8. 학습용과 테스트용 데이터셋으로 나누기
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# 9. Logistic Regression 모델 생성 및 학습
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

# 10. 예측 및 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

KeyboardInterrupt: 

In [79]:
# 1. 데이터 로드
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "income",
]
data = pd.read_csv(
    url, header=None, names=columns, na_values="?", skipinitialspace=True
)  # ?는 널값으로 처리

In [80]:
data.to_csv("adult_incomes.csv", index=False)

In [113]:
data = pd.read_csv('adult_incomes.csv')

In [114]:
data.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [115]:
#결측치 제거

data.dropna(inplace=True)

In [ ]:
data

In [118]:
data['capital-gain'].describe()

count    30162.000000
mean      1092.007858
std       7406.346497
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      99999.000000
Name: capital-gain, dtype: float64

In [119]:
# 이상치 제거 data['capital-gain'] max값 제거
data = data[data['capital-gain'] < 99990]

In [ ]:
data

In [112]:
import pandas as pd
import numpy as np


def remove_outliers(data, columns):
    outlier_indices = set()
    for col in columns:
        q1 = data[col].quantile(0.25)
        q3 = data[col].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        # 0이 아닌 값에 대해서만 이상치 검출
        outliers = data[
            (data[col] < lower_bound) | (data[col] > upper_bound) & (data[col] != 0)
        ]
        outlier_indices.update(outliers.index)
        print(f"Number of outliers in {col}: {len(outliers)}")

    data_clean = data.drop(outlier_indices)
    print(f"Total number of outliers removed: {len(outlier_indices)}")
    return data_clean.reset_index(drop=True)


# 사용 예:
data_clean = remove_outliers(data, ["capital-gain", "capital-loss"])

Number of outliers in capital-gain: 2538
Number of outliers in capital-loss: 1427
Total number of outliers removed: 3965


In [107]:
# 이상치 제거 capital
q1 = data["capital-gain"].quantile(0.25)
q3 = data["capital-gain"].quantile(0.75)
iqr = q3 - q1
capital_gain_outlier = data[
    (data["capital-gain"] < q1 - 1.5 * iqr) | (data["capital-gain"] > q3 + 1.5 * iqr)
]
print(len(capital_gain_outlier))

q1 = data["capital-loss"].quantile(0.25)
q3 = data["capital-loss"].quantile(0.75)
iqr = q3 - q1
capital_loss_outlier = data[
    (data["capital-loss"] < q1 - 1.5 * iqr) | (data["capital-loss"] > q3 + 1.5 * iqr)
]
print(len(capital_loss_outlier))
data = data.drop(capital_gain_outlier.index)
data = data.drop(capital_loss_outlier.index)

2538
1427


In [108]:
data

age         workclass  fnlwgt     education  education-num  \
1       50  Self-emp-not-inc   83311     Bachelors             13   
2       38           Private  215646       HS-grad              9   
3       53           Private  234721          11th              7   
4       28           Private  338409     Bachelors             13   
5       37           Private  284582       Masters             14   
...    ...               ...     ...           ...            ...   
32555   22           Private  310152  Some-college             10   
32556   27           Private  257302    Assoc-acdm             12   
32557   40           Private  154374       HS-grad              9   
32558   58           Private  151910       HS-grad              9   
32559   22           Private  201490       HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
5      Married-civ-spouse    Exec-managerial           Wife  White  Female   
...                   ...                ...            ...    ...     ...   
32555       Never-married    Protective-serv  Not-in-family  White    Male   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   

       capital-gain  capital-loss  hours-per-week native-country income  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
5                 0             0              40  United-States  <=50K  
...             ...           ...             ...            ...    ...  
32555             0             0              40  United-States  <=50K  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  

[26197 rows x 15 columns]

In [120]:
# 파생변수 작성
data["capital_diff"] = data["capital-gain"] - data["capital-loss"]

In [121]:
# data["capital-gain"],  data["capital-loss"] 삭제

data = data.drop(["capital-gain"], axis=1)


In [122]:
data = data.drop(["capital-loss"], axis=1)

In [123]:
data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       hours-per-week native-country income  capital_diff  
0                  40  United-States  <=50K          2174  
1                  13  United-States  <=50K             0  
2                  40  United-States  <=50K             0  
3                  40  United-States  <=50K             0  
4                  40           Cuba  <=50K             0  
...               ...            ...    ...           ...  
32556              38  United-States  <=50K             0  
32557              40  United-States   >50K             0  
32558              40  United-States  <=50K             0  
32559              20  United-States  <=50K             0  
32560              40  United-States   >50K         15024  

[30014 rows x 14 columns]

In [124]:
# 범주형 변수 인코딩
categorical_features = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
    "income",
]
data = pd.get_dummies(data, columns=categorical_features, drop_first=True)

In [125]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30014 entries, 0 to 32560
Data columns (total 96 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   age                                        30014 non-null  int64
 1   fnlwgt                                     30014 non-null  int64
 2   education-num                              30014 non-null  int64
 3   hours-per-week                             30014 non-null  int64
 4   capital_diff                               30014 non-null  int64
 5   workclass_Local-gov                        30014 non-null  bool 
 6   workclass_Private                          30014 non-null  bool 
 7   workclass_Self-emp-inc                     30014 non-null  bool 
 8   workclass_Self-emp-not-inc                 30014 non-null  bool 
 9   workclass_State-gov                        30014 non-null  bool 
 10  workclass_Without-pay                      30014 no

In [126]:
# 변수 선택및 독립변수 , 종속변수 분리
X = data.drop("income_>50K", axis=1)
y = data["income_>50K"]

In [127]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [128]:
# 데이터셋 분리
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [129]:
# Logistic Regression 모델 생성 및 학습합니다.
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [130]:
# 예측 및 평가합니다. - 정확도, 리포트
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {round(accuracy,4)}")
print("Confusion Matrix:")
print(conf_matrix, "\n")
print("Classification Report:")
print(class_report, "\n")

Accuracy: 0.8431
Confusion Matrix:
[[4208  331]
 [ 611  853]] 

Classification Report:
              precision    recall  f1-score   support

       False       0.87      0.93      0.90      4539
        True       0.72      0.58      0.64      1464

    accuracy                           0.84      6003
   macro avg       0.80      0.75      0.77      6003
weighted avg       0.84      0.84      0.84      6003
 

