Task1_0827. 2행 3열 텐서의 크기를 3행 2열로 변경하세요.
- view 사용
- reshape 사용
- transpose 사용

In [1]:
import torch

t = torch.rand(2, 3)
print(t)
print(t.size())

tensor([[0.3824, 0.1110, 0.4113],
        [0.2812, 0.8575, 0.9967]])
torch.Size([2, 3])


In [3]:
# view

v = t.view(3, -1)
print(v)
print(v.size())

tensor([[0.6031, 0.4349],
        [0.4523, 0.6357],
        [0.0878, 0.2939]])
torch.Size([3, 2])


In [5]:
# reshape

r = t.reshape(3, -1)
print(r)
print(r.size())

tensor([[0.6031, 0.4349],
        [0.4523, 0.6357],
        [0.0878, 0.2939]])
torch.Size([3, 2])


In [12]:
# transpose

tr = t.transpose(-2,1)
print(tr)
print(tr.size())

tensor([[0.6031, 0.6357],
        [0.4349, 0.0878],
        [0.4523, 0.2939]])
torch.Size([3, 2])


# ex

In [3]:
import torch

tensor = torch.randn(2,3)
print("original tensor: ", tensor.shape)

viewed_tensor = tensor.view(3,2)
print("viewed tensor: ", viewed_tensor.shape)

# reshape는 view와 같은 역할을 하지만, 메모리를 새로 할당한다.
reshaped_tensor = tensor.reshape(3,2)
print("reshaped tensor: ", reshaped_tensor.shape)

transposed_tensor = tensor.transpose(0,1) #행과 열을 바꿔줌
print("transposed tensor: ", transposed_tensor.shape)

original tensor:  torch.Size([2, 3])
viewed tensor:  torch.Size([3, 2])
reshaped tensor:  torch.Size([3, 2])
transposed tensor:  torch.Size([3, 2])
